### ISSUE TITLE
Disable 'pull to refresh'

### ISSUE THREAD

**Issue by Ahplla** [cloversalad/cloversalad#1]
Firstly, I want to congratulate you on the excellent work!!! I suggest implementing CSS or JavaScript to disable the 'pull to refresh' on the page. Due to the responsiveness limitations of browsers, navigating through the content as it is often results in refreshing the page instead of smoothly scrolling down, and my suggestion would resolve that. I have forked the project, and I hope to contribute more with you in the future.

**Comment by Ahplla** [comment]
p.s. the shortcut button for your discord is not working, it doesn't take you to your profile

**Comment by cloversalad** [comment]
Thanks a lot !
Feel free to submit PR whenever you want <3
